# Generated by Django 6.0.3 on 2026-04-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_marketing_staff_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_investor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_marketing_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('investor', 'Investor'), ('employee', 'Employee'), ('marketing', 'Marketing Staff')], default='customer', max_length=20),
        ),
    ]
