# Generated by Django 6.0.3 on 2026-04-08 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('developer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField()),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use')], default='residential', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('under_construction', 'Under Construction'), ('ready', 'Ready to Move')], default='upcoming', max_length=20)),
                ('building_type', models.CharField(choices=[('single_building', 'Single Building'), ('multi_building_complex', 'Multi Building Complex'), ('skyscraper', 'Skyscraper')], default='single_building', max_length=50)),
                ('total_share', models.PositiveIntegerField(default=0, help_text='Total ownership shares')),
                ('unit_per_floor', models.PositiveIntegerField(default=0)),
                ('has_lift', models.BooleanField(default=True, verbose_name='Lift/Elevator Available')),
                ('has_rooftop_access', models.BooleanField(default=True, verbose_name='Rooftop Facility')),
                ('has_convention_hall', models.BooleanField(default=False, verbose_name='Convention/Community Hall')),
                ('has_electricity_backup', models.BooleanField(default=True, verbose_name='Generator/Electricity Backup')),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('land_area', models.CharField(help_text='Example: 10 Katha', max_length=100)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unit_number', models.CharField(max_length=50)),
                ('size_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor_level', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='available', max_length=15)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='projects.project')),
            ],
        ),
    ]
