# Generated by Django 6.0.3 on 2026-04-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_dining_room',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_drawing_room',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_electricity_backup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_hall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_kitchen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_lift',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
        migrations.AddField(
            model_name='property',
            name='road',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
