# Generated by Django 6.0.3 on 2026-04-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('review_text', models.TextField(blank=True, help_text='Client feedback or review', null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating out of 5')),
                ('video', models.FileField(blank=True, null=True, upload_to='client_reviews/videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='client_reviews/images/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
